language: node_js

node_js:
  - 12.13

before_install:
  - nvm install node
  - npm install -g npm@latest

install:
  - npm install

script:
  - grunt
  - mv -Rf build deploy

deploy:
  provider: pages
  local-dir: deploy
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master